using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Threading.Tasks;
using ChangeDB.Migration;
using FluentAssertions;
using TestDB;
using Xunit;

namespace ChangeDB.Agent.Postgres
{
    public class PostgresDataMigratorTest : BaseTest, IDisposable
    {

        private readonly PostgresDataMigrator _dataMigrator = PostgresDataMigrator.Default;
        private readonly AgentContext _agentContext = new AgentContext();
        private readonly DbConnection _dbConnection;
        private readonly IDatabase database;


        public PostgresDataMigratorTest(DatabaseEnvironment databaseEnvironment)
        {
            database = CreateDatabase(false);

            _dbConnection = database.Connection;

            _agentContext = new AgentContext
            {
                Connection = _dbConnection,
            };

        }
        public void Dispose()
        {
            database.Dispose();
        }

        [Fact]
        public async Task ShouldReturnTableRowCountWhenCountTable()
        {
            _dbConnection.ExecuteNonQuery(
                "create schema ts;",
                "create table ts.table1(id int primary key,nm varchar(64));",
                "INSERT INTO ts.table1(id,nm) VALUES(1,'name1');",
                "INSERT INTO ts.table1(id,nm) VALUES(2,'name2');",
                "INSERT INTO ts.table1(id,nm) VALUES(3,'name3');"
            );

            var rows = await _dataMigrator.CountSourceTable(new TableDescriptor
            {
                Name = "table1",
                Schema = "ts",
            }, _agentContext);
            rows.Should().Be(3);
        }

        [Fact]
        public async Task ShouldReturnDataTableWhenReadTableData()
        {
            _dbConnection.ExecuteNonQuery(
                "create schema ts;",
                "create table ts.table1(id int primary key,nm varchar(64));",
                "INSERT INTO ts.table1(id,nm) VALUES(1,'name1');",
                "INSERT INTO ts.table1(id,nm) VALUES(2,'name2');",
                "INSERT INTO ts.table1(id,nm) VALUES(3,'name3');"
            );
            var table = await _dataMigrator.ReadSourceTable(new TableDescriptor { Name = "table1", Schema = "ts", },
                new PageInfo { Limit = 1, Offset = 1 }, _agentContext);
            table.Rows.Count.Should().Be(1);
            table.Rows[0]["id"].Should().Be(2);
            table.Rows[0]["nm"].Should().Be("name2");
        }
        [Fact]
        public async Task ShouldSuccessWhenWriteTableData()
        {
            _dbConnection.ExecuteNonQuery(
                "create schema ts;",
                "create table ts.table1(id int primary key,nm varchar(64));"
            );
            var table = new DataTable();
            table.Columns.Add("id", typeof(int));
            table.Columns.Add("nm", typeof(string));
            var row = table.NewRow();
            row["id"] = 4;
            row["nm"] = "name4";
            table.Rows.Add(row);
            var tableDescriptor = new TableDescriptor
            {
                Schema = "ts",
                Name = "table1",
                Columns = new List<ColumnDescriptor>
                {
                    new ColumnDescriptor{ Name = "id",DataType = DataTypeDescriptor.Int()},
                    new ColumnDescriptor{Name = "nm",DataType = DataTypeDescriptor.Varchar(64)}
                }
            };
            await WriteTargetTable(table, tableDescriptor, _agentContext);
            var data = _dbConnection.ExecuteReaderAsList<int, string>("select * from ts.table1");
            data.Should().BeEquivalentTo(new List<Tuple<int, string>> { new Tuple<int, string>(4, "name4") });
        }

        [Fact]
        public async Task ShouldInsertIdentityByDefaultColumn()
        {
            _dbConnection.ExecuteNonQuery(
                "create schema ts;",
                "create table ts.table1(id int generated by default as identity primary key ,nm varchar(64));"
            );
            var table = new DataTable();
            table.Columns.Add("id", typeof(int));
            table.Columns.Add("nm", typeof(string));
            var row = table.NewRow();
            row["id"] = 1;
            row["nm"] = "name1";
            table.Rows.Add(row);
            var tableDescriptor = new TableDescriptor
            {
                Schema = "ts",
                Name = "table1",
                Columns = new List<ColumnDescriptor>
                {
                    new ColumnDescriptor
                    {
                        Name = "id", DataType  = DataTypeDescriptor.Int(), IsIdentity = true,
                        IdentityInfo = new IdentityDescriptor
                        {
                            IsCyclic =false,
                            Values = new Dictionary<string, object>
                            {
                                [PostgresUtils.IdentityType]="BY DEFAULT",
                            },
                            CurrentValue = 5
                        }
                    },
                    new ColumnDescriptor{Name = "nm",DataType =DataTypeDescriptor.Varchar(64)}
                }
            };
            await WriteTargetTable(table, tableDescriptor, _agentContext);
            _dbConnection.ExecuteNonQuery("insert into ts.table1(nm) values('name6')");
            var data = _dbConnection.ExecuteReaderAsList<int, string>("select * from ts.table1");
            data.Should().BeEquivalentTo(new List<Tuple<int, string>> { new(1, "name1"), new(6, "name6") });
        }

        [Fact]
        public async Task ShouldInsertIdentityAlwaysColumn()
        {
            _dbConnection.ExecuteNonQuery(
                "create schema ts;",
                "create table ts.table1(id int generated always as identity primary key ,nm varchar(64));"
            );
            var table = new DataTable();
            table.Columns.Add("id", typeof(int));
            table.Columns.Add("nm", typeof(string));
            var row = table.NewRow();
            row["id"] = 1;
            row["nm"] = "name1";
            table.Rows.Add(row);
            var tableDescriptor = new TableDescriptor
            {
                Schema = "ts",
                Name = "table1",
                Columns = new List<ColumnDescriptor>
                {
                    new ColumnDescriptor
                    {
                        Name = "id", DataType  = DataTypeDescriptor.Int(), IsIdentity = true,
                        IdentityInfo = new IdentityDescriptor
                        {
                            IsCyclic =false,
                            Values = new Dictionary<string, object>
                            {
                                [PostgresUtils.IdentityType]="ALWAYS",
                            },
                            CurrentValue = 5
                        }
                    },
                    new ColumnDescriptor{Name = "nm",DataType =DataTypeDescriptor.Varchar(64)}
                }
            };
            await WriteTargetTable(table, tableDescriptor, _agentContext);
            _dbConnection.ExecuteNonQuery("insert into ts.table1(nm) values('name6')");
            var data = _dbConnection.ExecuteReaderAsList<int, string>("select * from ts.table1");
            data.Should().BeEquivalentTo(new List<Tuple<int, string>> { new(1, "name1"), new(6, "name6") });
        }

        private async Task WriteTargetTable(DataTable data, TableDescriptor tableDescriptor,
            AgentContext agentContext)
        {
            await _dataMigrator.BeforeWriteTable(tableDescriptor, agentContext);
            await _dataMigrator.WriteTargetTable(data, tableDescriptor, agentContext);
            await _dataMigrator.AfterWriteTable(tableDescriptor, agentContext);
        }

    }
}
